// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKU3hMM5g_KELwZlmRFygljfnrzpZtSw',
    appId: '1:621074647929:web:fcdc135222d06244517da8',
    messagingSenderId: '621074647929',
    projectId: 'acara37-bec37',
    authDomain: 'acara37-bec37.firebaseapp.com',
    databaseURL: 'https://acara37-bec37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'acara37-bec37.appspot.com',
    measurementId: 'G-NE7BC6MJDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SSaONLTtCO2FJMDwE8AMyFAFDGE7yw4',
    appId: '1:621074647929:android:ffe52945d30fb8d1517da8',
    messagingSenderId: '621074647929',
    projectId: 'acara37-bec37',
    databaseURL: 'https://acara37-bec37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'acara37-bec37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYZEBnB9ot1d7fAiQgMU5hsWgmUCHxyY',
    appId: '1:621074647929:ios:d6c9f8a1179e4539517da8',
    messagingSenderId: '621074647929',
    projectId: 'acara37-bec37',
    databaseURL: 'https://acara37-bec37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'acara37-bec37.appspot.com',
    iosClientId: '621074647929-9i7bflejgdqddp0tik6jv8u3lvehrgvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.acara37',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkYZEBnB9ot1d7fAiQgMU5hsWgmUCHxyY',
    appId: '1:621074647929:ios:d6c9f8a1179e4539517da8',
    messagingSenderId: '621074647929',
    projectId: 'acara37-bec37',
    databaseURL: 'https://acara37-bec37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'acara37-bec37.appspot.com',
    iosClientId: '621074647929-9i7bflejgdqddp0tik6jv8u3lvehrgvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.acara37',
  );
}
